name: leontech
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  get: ^4.6.6
  encrypt: ^5.0.3
  cached_network_image: ^3.4.1
  mime: ^2.0.0
  collection: ^1.18.0
  http: ^1.2.2
  infinite_scroll_pagination: ^4.1.0
  currency_text_input_formatter: ^2.2.6
  photo_view: ^0.15.0
  flutter_spinbox: ^0.13.1
  auto_size_text: ^3.0.0
  flutter_carousel_widget: ^3.1.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  file_picker: ^8.1.4
  google_sign_in_dartio: ^0.3.0
  flutter_native_splash: ^2.4.3
  video_player: ^2.9.2
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.0
  flutter_animate: ^4.5.1
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  firebase_data_connect: ^0.1.2+3

flutter:
  uses-material-design: true
  assets:
    - assets/
 
  shaders:
    - assets/shader.frag